version: 2.1
jobs:
  test-in-java9-module-safe:
    docker:
      - image: openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo '127.0.0.1 www.a.com' >> /etc/hosts
            ./gradlew testModuleSafe
      - store_artifacts:
          path: build/tests-module-safe/
          destination: build-reports-java9-module-safe

  test-in-java9-requires-add-opens:
    docker:
      - image: openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo '127.0.0.1 www.a.com' >> /etc/hosts
            ./gradlew testRequiresAddOpens
      - store_artifacts:
          path: build/tests-requires-add-open/
          destination: build-reports-java9-requires-add-opens

  build:
    machine:
      image: ubuntu-2004:2024.08.1
      docker_layer_caching: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:RsiwAXfsyThB7csOUCQMDj92/KopbaHoxYY5olkmWF8'
      - checkout
      - run:
          name: env
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-17-jdk
            sudo docker-compose up -d
            sudo bash -c "echo '127.0.0.1 www.s.com' >> /etc/hosts"
            sudo bash -c "echo '127.0.0.1 www.a.com' >> /etc/hosts"
      - run:
          name: build
          command: |
            export CI=true
            export DAL_INSPECTOR_WAITING_TIME=30000
            sudo chmod 777 /tmp/testcharm
            ./gradlew test build uploadCoverage --parallel
            export PUB_VERSION=$(./gradlew currentVersion -q)
            if ( bash -c "git tag | grep -q \"^${PUB_VERSION}$\"" ); then
              echo "====== Still version ${PUB_VERSION}, CI done ======"
              exit 0
            fi
            echo "====== Release and tag new version $PUB_VERSION ======"
            ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --info
            git config --global user.email "leeonky@gmail.com"
            git config --global user.name "leeonky"
            git tag ${PUB_VERSION} -a -m 'CI Release'
            git push --tags

      - store_artifacts:
          path: build/tests/
          destination: build-reports

workflows:
  all-build:
    jobs:
      - test-in-java9-module-safe:
          filters:
            branches:
              only:
                - main
      - test-in-java9-requires-add-opens:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - test-in-java9-module-safe
            - test-in-java9-requires-add-opens
          filters:
            branches:
              only:
                - main
